### ISSUE TITLE
gin的Group()返回的类型和swagger.Swagger2()用到的类型不太一样啊

### ISSUE THREAD

**Issue by easternK** [qjw/go-swagger-doc#1]
gin的Group()返回的数据类型是`*RouterGroup`，而
https://github.com/qjw/go-swagger-doc/blob/904b54e9f38acdc0d13a8aec931b4bae248769ef/api.go#L102-L105
第一个参数类型是 ` *gin.RouterGroup`
请问这个 *gin.RouterGroup这个能从哪里能获取啊

**Comment by easternK** [comment]
原来是引入的gin包地址不一样造成的，打扰了...

**Comment by qjw** [comment]
go的这个特性有点坑爹，要不都从vendor获取，要不都不从vendor，两边的路径下都有这个包，就会出现这种问题，注意下就好
